[build-system]
requires = ["hatchling", "versioningit~=2.0"]
build-backend = "hatchling.build"

# Self-descriptive entries which should always be present
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
[project]
name = "SoAPy"
description = "A package for research on SOlvation Algorithms in PYthon, SoAPy."
dynamic = ["version"]
readme = "README.md"
authors = [
    { name = "Brendan Shumberger", email = "bshumberger@vt.edu" }
]
license = { text = "BSD-3-Clause" }
# See https://pypi.org/classifiers/
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
# Declare any run-time dependencies that should be installed with the package.
#dependencies = [
#   "importlib-resources;python_version<'3.10'",
#]

# Update the urls once the hosting is set up.
#[project.urls]
#"Source" = "https://github.com/<username>/SoAPy/"
#"Documentation" = "https://SoAPy.readthedocs.io/"

[project.optional-dependencies]
test = [
  "pytest>=6.1.2",
  "pytest-runner"
]

[tool.versioningit]
default-version = "1+unknown"

[tool.versioningit.format]
distance = "{base_version}+{distance}.{vcs}{rev}"
dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
distance-dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"

[tool.versioningit.vcs]
# The method key:
method = "git"  # <- The method name
# Parameters to pass to the method:
match = ["*"]
default-tag = "1.0.0"

[tool.versioningit.write]
file = "SoAPy/_version.py"
